[env]
TERM = "alacritty"

[window]
padding.x = 3
padding.y = 3
dynamic_padding = false

opacity = 0.98
decorations="None"
startup_mode="Maximized"

[font]
normal.family = "FiraCode Nerd Font Mono Light"
size = 18

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material.toml"
]
