[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = false

#decorations = "None"
#startup_mode = "Maximized"

opacity = 0.95
#blur = true

[font]
normal.family = "FiraCode Nerd Font Light"
#normal.family = "JetBrainsMono NF ExtraLight"
#normal.family = "Hack Nerd Font Mono"
size = 20

[general]
import = [
    #"~/.config/alacritty/themes/themes/gruvbox_dark.toml"
    "~/.config/alacritty/themes/themes/gruvbox_material.toml"
    #"~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml.toml"
    #"~/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml.toml"
]
