[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.7
blur = true

[font]
normal.family = "Inconsolata"
size = 20

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
