[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = false

decorations = "None"
startup_mode = "Maximized"

opacity = 0.97
blur = true

[font]
normal.family = "Inconsolata"
size = 22

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
