[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = false

#decorations = "None"
#startup_mode = "Maximized"

opacity = 0.9
#blur = true

[font]
normal.family = "FiraCode Nerd Font Light"
size = 20

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
