[env]
TERM = "xterm-256color"

[window]
padding.x = 3
padding.y = 2
dynamic_padding = false

decorations = "None"
startup_mode = "Maximized"

opacity = 0.97
blur = true

[font]
normal.family = "FiraCode Nerd Font Light"
size = 22

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
