brew "bash"
brew "fd"
brew "fzf"
brew "gh"
brew "llvm"
brew "neovim"
brew "ripgrep"
brew "rsync"
brew "tmux"
brew "git"
brew "stow"

cask "alacritty"

cask "font-fira-code-nerd-font"
cask "font-fira-mono-nerd-font"
cask "font-inconsolata-nerd-font"
cask "font-jetbrains-mono-nerd-font"
