[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
dynamic_padding = false

opacity = 0.95
decorations="buttonless"
startup_mode="Maximized"

[font]
normal.family = "FiraCode Nerd Font Light"
size = 18

[general]
import = [
    "~/.config/alacritty/themes/themes/gruvbox_material.toml"
]
