# tmux-ssh-split options
set-option -g @ssh-split-keep-cwd "true"
set-option -g @ssh-split-keep-remote-cwd "true"
set-option -g @ssh-split-fail "false"
set-option -g @ssh-split-no-env "false"
set-option -g @ssh-split-no-shell "false"
set-option -g @ssh-split-strip-cmd "true"
set-option -g @ssh-split-verbose "true"
set-option -g @ssh-split-debug "false"
set-option -g @ssh-split-h-key "v"
set-option -g @ssh-split-v-key "s"

set -g @fingers-key f

# List of plugins with TPM
# Reminder: Prefix Shift+I to install the plugins after being listed here.
# Note: This alternate syntax is required because we launch tmux with -f to specify the config file
# This is a known issue per https://github.com/tmux-plugins/tpm/blob/master/docs/tpm_not_working.md
# https://github.com/tmux-plugins/tpm/issues/57
set -g @tpm_plugins '          \
  tmux-plugins/tpm             \
  pschmitt/tmux-ssh-split      \
  Morantron/tmux-fingers       \
'

# Setup the directory to store plugins
PLUGIN_PATH="${HOME}/.local/share/tmux_plugins/"
if "test ! -d ${PLUGIN_PATH}" \
    "run 'mkdir ${PLUGIN_PATH}'"
set-environment -g TMUX_PLUGIN_MANAGER_PATH "${PLUGIN_PATH}"

# Install TPM if not already present
TPM="${PLUGIN_PATH}/tpm"
if "test ! -d ${TPM}" \
    "run 'git clone https://github.com/tmux-plugins/tpm ${TPM} && ${TPM}/bin/install_plugins'"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '${TPM}/tpm'
